complete -c database -f -a 'auth login'
complete -c database -f -a 'auth logout'
complete -c database -f -a 'base activate'
complete -c database -f -a 'base create'
complete -c database -f -a 'base delete'
complete -c database -f -a 'base describe'
complete -c database -f -a 'base legacy-migration apply'
complete -c database -f -a 'base legacy-migration plan'
complete -c database -f -a 'base list'
complete -c database -f -a 'base placement apply'
complete -c database -f -a 'base placement plan'
complete -c database -f -a 'base placements'
complete -c database -f -a 'base retire'
complete -c database -f -a 'capabilities'
complete -c database -f -a 'command run'
complete -c database -f -a 'completion bash'
complete -c database -f -a 'completion fish'
complete -c database -f -a 'completion zsh'
complete -c database -f -a 'composition create'
complete -c database -f -a 'composition delete'
complete -c database -f -a 'composition describe'
complete -c database -f -a 'composition list'
complete -c database -f -a 'composition replace'
complete -c database -f -a 'doctor'
complete -c database -f -a 'entity apply'
complete -c database -f -a 'entity delete'
complete -c database -f -a 'entity insert'
complete -c database -f -a 'entity update'
complete -c database -f -a 'entity upsert'
complete -c database -f -a 'fdb'
complete -c database -f -a 'grant add'
complete -c database -f -a 'grant direct'
complete -c database -f -a 'grant effective'
complete -c database -f -a 'grant revoke'
complete -c database -f -a 'graph community'
complete -c database -f -a 'graph cycles'
complete -c database -f -a 'graph page-rank'
complete -c database -f -a 'graph shortest-path'
complete -c database -f -a 'graph strongly-connected-components'
complete -c database -f -a 'graph topological-sort'
complete -c database -f -a 'graph weighted-shortest-path'
complete -c database -f -a 'index rebuild'
complete -c database -f -a 'index status'
complete -c database -f -a 'inspect entities'
complete -c database -f -a 'inspect graph'
complete -c database -f -a 'inspect indexes'
complete -c database -f -a 'inspect jobs'
complete -c database -f -a 'inspect ontology'
complete -c database -f -a 'inspect overview'
complete -c database -f -a 'inspect shapes'
complete -c database -f -a 'job cancel'
complete -c database -f -a 'job result'
complete -c database -f -a 'job status'
complete -c database -f -a 'job wait'
complete -c database -f -a 'maintenance compact'
complete -c database -f -a 'migration run'
complete -c database -f -a 'migration status'
complete -c database -f -a 'mutate sparql'
complete -c database -f -a 'mutate sql'
complete -c database -f -a 'ontology delete'
complete -c database -f -a 'ontology describe'
complete -c database -f -a 'ontology hierarchy'
complete -c database -f -a 'ontology reason'
complete -c database -f -a 'ontology upsert'
complete -c database -f -a 'ontology validate-schema'
complete -c database -f -a 'open'
complete -c database -f -a 'profile create'
complete -c database -f -a 'profile list'
complete -c database -f -a 'profile remove'
complete -c database -f -a 'profile show'
complete -c database -f -a 'profile use'
complete -c database -f -a 'query sparql'
complete -c database -f -a 'query sql'
complete -c database -f -a 'schema apply'
complete -c database -f -a 'schema list'
complete -c database -f -a 'schema plan'
complete -c database -f -a 'schema show'
complete -c database -f -a 'serve'
complete -c database -f -a 'shacl delete'
complete -c database -f -a 'shacl describe'
complete -c database -f -a 'shacl upsert'
complete -c database -f -a 'shacl validate'
complete -c database -f -a 'shell'
complete -c database -f -a 'version'
