import Foundation
import Testing
@testable import DatabaseCommandLine

@Suite("Command catalog")
struct CommandCatalogTests {
    @Test("catalog paths and option names are unique and every contract resolves")
    func catalogIsInternallyConsistent() throws {
        let catalog = CommandCatalog.standard
        #expect(Set(catalog.commands.map(\.path)).count == catalog.commands.count)
        for command in catalog.commands {
            let names = Set(command.options.map(\.name))
            #expect(names.count == command.options.count)
            for option in command.options {
                #expect(option.minimumOccurrences >= 0)
                if let maximum = option.maximumOccurrences {
                    #expect(maximum >= option.minimumOccurrences)
                }
                #expect(option.conflictsWith.isSubset(of: names))
                #expect(option.requires.isSubset(of: names))
            }
            for requirement in command.requiredAnyOf {
                #expect(!requirement.isEmpty)
                #expect(requirement.isSubset(of: names))
            }
        }
    }

    @Test("nested help is generated from the same required option descriptors")
    func nestedHelpShowsExactContracts() throws {
        let result = try captureResult { output in
            try DatabaseCLIApplication(output: output)
                .showHelp(["graph", "shortest-path"])
        }

        #expect(result.contains("database graph shortest-path"))
        #expect(result.contains("--index <name>"))
        #expect(result.contains("--source <typed-graph-term>"))
        #expect(result.contains("--target <typed-graph-term>"))
        #expect(result.contains("required"))
        #expect(!result.contains("--damping-factor"))
        #expect(!result.contains("--compute-modularity"))
        #expect(!result.contains("--parameter"))
        #if DATABASE_CLI_MULTIPLE_BASES
        #expect(result.contains("--base <id>"))
        #else
        #expect(!result.contains("--base <id>"))
        #endif
    }

    #if DATABASE_CLI_MULTIPLE_BASES
    @Test("explicit target choices are generated by the MultipleBases catalog")
    func targetChoicesAreCatalogDriven() throws {
        let queryHelp = try captureResult { output in
            try DatabaseCLIApplication(output: output)
                .showHelp(["query", "sql"])
        }
        #expect(queryHelp.contains("--base <id>"))
        #expect(queryHelp.contains("--composition <id>"))
        #expect(queryHelp.contains("one of: --base, --composition"))

        let grantHelp = try captureResult { output in
            try DatabaseCLIApplication(output: output)
                .showHelp(["grant", "effective"])
        }
        #expect(grantHelp.contains("--base <id>"))
        #expect(grantHelp.contains("--database-target"))
        #expect(!grantHelp.contains("--principal"))
        #expect(!grantHelp.contains("--role"))
    }
    #else
    @Test("single-database catalog contains no Base targeting surface")
    func singleDatabaseCatalogHasNoBaseTargeting() throws {
        let queryHelp = try captureResult { output in
            try DatabaseCLIApplication(output: output)
                .showHelp(["query", "sql"])
        }
        #expect(!queryHelp.contains("--base <id>"))
        #expect(!queryHelp.contains("--composition <id>"))
        #expect(CommandCatalog.standard.command(for: ["base", "list"]) == nil)
        #expect(
            CommandCatalog.standard.command(for: ["composition", "list"])
                == nil
        )
        #expect(CommandCatalog.standard.command(for: ["grant", "direct"]) == nil)
    }
    #endif

    @Test("each graph algorithm exposes only its own execution controls")
    func graphOptionsAreAlgorithmSpecific() throws {
        let catalog = CommandCatalog.standard
        let shortest = try #require(
            catalog.command(for: ["graph", "shortest-path"])
        )
        let pageRank = try #require(
            catalog.command(for: ["graph", "page-rank"])
        )
        let community = try #require(
            catalog.command(for: ["graph", "community"])
        )

        #expect(shortest.option(named: "source") != nil)
        #expect(shortest.option(named: "damping-factor") == nil)
        #expect(pageRank.option(named: "damping-factor") != nil)
        #expect(pageRank.option(named: "source") == nil)
        #expect(community.option(named: "compute-modularity") != nil)
        #expect(community.option(named: "maximum-cycles") == nil)
    }

    @Test("non-paged commands do not advertise paging controls")
    func pagingOptionsAreCommandSpecific() throws {
        let catalog = CommandCatalog.standard
        let query = try #require(catalog.command(for: ["query", "sql"]))
        let mutation = try #require(catalog.command(for: ["mutate", "sql"]))
        let wait = try #require(catalog.command(for: ["job", "wait"]))
        let migration = try #require(
            catalog.command(for: ["migration", "run"])
        )

        #expect(query.option(named: "page-size") != nil)
        #expect(query.option(named: "all") != nil)
        #expect(mutation.option(named: "page-size") == nil)
        #expect(mutation.option(named: "all") == nil)
        #expect(wait.option(named: "as-job") == nil)
        #expect(wait.option(named: "continuation") == nil)
        #expect(migration.option(named: "continuation") != nil)
        #expect(migration.option(named: "page-size") == nil)
    }

    @Test("every static completion is generated from every catalog path", arguments: [
        "bash", "zsh", "fish",
    ])
    func completionContainsEveryCatalogPath(_ shell: String) throws {
        let catalog = CommandCatalog.standard
        let completion = try CompletionGenerator(catalog: catalog)
            .generate(for: shell)

        for command in catalog.commands where command.path != ["help"] {
            #expect(completion.contains(command.path.joined(separator: " ")))
        }
        #expect(!completion.contains("https://"))
        #expect(!completion.contains("curl "))
    }

    #if !DATABASE_CLI_MULTIPLE_BASES
    @Test("checked-in completions exactly match the single-database catalog")
    func checkedInCompletionsMatchGenerator() throws {
        let root = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let fixtures = [
            (shell: "bash", path: "Completions/database.bash"),
            (shell: "zsh", path: "Completions/_database"),
            (shell: "fish", path: "Completions/database.fish"),
        ]
        let generator = CompletionGenerator(catalog: .standard)

        for fixture in fixtures {
            let checkedIn = try String(
                contentsOf: root.appendingPathComponent(fixture.path),
                encoding: .utf8
            )
            let generated = try generator.generate(for: fixture.shell)
            #expect(checkedIn == generated)
        }
    }
    #endif

    @Test("command reference names every public catalog path")
    func commandReferenceCoversCatalog() throws {
        let root = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let reference = try String(
            contentsOf: root.appendingPathComponent(
                "Documentation/Commands.md"
            ),
            encoding: .utf8
        )

        for command in CommandCatalog.standard.commands {
            let spelling = "`database "
                + command.path.joined(separator: " ")
            #expect(
                reference.contains(spelling),
                "Missing command reference for \(spelling)"
            )
        }
    }
}

private func captureResult(
    _ body: (OutputWriter) throws -> Void
) throws -> String {
    let url = FileManager.default.temporaryDirectory
        .appendingPathComponent(Foundation.UUID().uuidString)
    guard FileManager.default.createFile(atPath: url.path, contents: nil) else {
        throw DatabaseCLIError(.internalFailure, "Unable to create test output")
    }
    let handle = try FileHandle(forWritingTo: url)
    do {
        try body(
            OutputWriter(
                resultHandle: handle,
                diagnosticHandle: .nullDevice
            )
        )
        try handle.close()
        let data = try Data(contentsOf: url)
        try FileManager.default.removeItem(at: url)
        guard let result = String(data: data, encoding: .utf8) else {
            throw DatabaseCLIError(.internalFailure, "Test output is not UTF-8")
        }
        return result
    } catch let operationError {
        do {
            try handle.close()
        } catch let closeError {
            throw closeError
        }
        do {
            try FileManager.default.removeItem(at: url)
        } catch let removalError {
            throw removalError
        }
        throw operationError
    }
}
